#pragma once

#include <algorithm>
#include <cmath>
#include <limits>
#include "wos/bessel.hpp"
#include "wos/prng.hpp"

namespace wos::screened {

constexpr double pi = 3.141592653589793238462643383279502884;

inline double weight_2d(double alpha, double radius) {
    const double x = alpha * radius;
    if (x == 0.0) return 1.0;
    if (x < 1e-3) {
        const double x2 = x * x;
        return 1.0 - x2 / 4.0 + 3.0 * x2 * x2 / 64.0;
    }
    return std::exp(-log_i0(x));
}

inline double green_2d(double alpha, double radius, double distance) {
    if (!(distance > 0.0) || distance > radius || radius <= 0.0) {
        return std::numeric_limits<double>::quiet_NaN();
    }
    if (distance == radius) return 0.0;

    const double x = alpha * distance;
    const double X = alpha * radius;
    if (X < 1e-5) {
        return std::log(radius / distance) / (2.0 * pi);
    }

    const double log_a = log_k0(x);
    const double log_b = log_i0(x) + log_k0(X) - log_i0(X);
    double delta = log_b - log_a;
    if (delta > 0.0) delta = 0.0;
    return std::exp(log_a) * (-std::expm1(delta)) / (2.0 * pi);
}

inline double mass_2d(double alpha, double radius) {
    const double x = alpha * radius;
    if (x < 1e-3) {
        const double x2 = x * x;
        return radius * radius
             * (1.0 / 4.0 - 3.0 * x2 / 64.0
                              + 19.0 * x2 * x2 / 2304.0);
    }
    return -std::expm1(-log_i0(x)) / (alpha * alpha);
}

inline double weight_3d(double alpha, double radius) {
    const double x = alpha * radius;
    if (x == 0.0) return 1.0;
    if (x < 1e-3) {
        const double x2 = x * x;
        return 1.0 - x2 / 6.0 + 7.0 * x2 * x2 / 360.0;
    }
    return 2.0 * x * std::exp(-x) / (-std::expm1(-2.0 * x));
}

inline double green_3d(double alpha, double radius, double distance) {
    if (!(distance > 0.0) || distance > radius || radius <= 0.0) {
        return std::numeric_limits<double>::quiet_NaN();
    }
    if (distance == radius) return 0.0;

    const double x = alpha * distance;
    const double X = alpha * radius;
    if (X < 1e-5) {
        return (radius - distance) / (4.0 * pi * distance * radius);
    }

    const double ratio = std::exp(-x)
                       * (-std::expm1(-2.0 * (X - x)))
                       / (-std::expm1(-2.0 * X));
    return ratio / (4.0 * pi * distance);
}

inline double mass_3d(double alpha, double radius) {
    const double x = alpha * radius;
    if (x < 1e-3) {
        const double x2 = x * x;
        return radius * radius
             * (1.0 / 6.0 - 7.0 * x2 / 360.0
                              + 31.0 * x2 * x2 / 15120.0);
    }
    return (1.0 - weight_3d(alpha, radius)) / (alpha * alpha);
}

inline double clamp_probability(double value) {
    return std::max(0.0, std::min(1.0, value));
}

inline double normal(PRNG &rng) {
    const double radius = std::sqrt(-2.0 * std::log(rng.unit_open()));
    const double angle = 2.0 * pi * rng.unit();
    return radius * std::cos(angle);
}

// Draw only the radius. The caller draws a uniform direction, keeping this
// code independent of the Point and Sphere types used by the WoS loop.
inline double sample_radius_2d(double alpha, double radius, PRNG &rng) {
    const double X = alpha * radius;
    for (;;) {
        double r;
        double acceptance;
        if (X < 2.0) {
            // Poisson Green proposal: p(r/R) = 4 s log(1/s).
            r = radius * std::sqrt(rng.unit_open() * rng.unit_open());
            const double proposal = std::log(radius / r) / (2.0 * pi);
            acceptance = green_2d(alpha, radius, r) / proposal;
        } else {
            // Infinite-space screened Green proposal, generated by sampling
            // an exponentially killed Brownian position.
            const double time = -std::log(rng.unit_open()) / (alpha * alpha);
            r = std::sqrt(-4.0 * time * std::log(rng.unit_open()));
            if (r >= radius) continue;

            const double x = alpha * r;
            const double log_ratio = log_i0(x) + log_k0(X)
                                   - log_i0(X) - log_k0(x);
            acceptance = -std::expm1(std::min(0.0, log_ratio));
        }
        if (rng.unit() < clamp_probability(acceptance)) return r;
    }
}

inline double sample_radius_3d(double alpha, double radius, PRNG &rng) {
    const double X = alpha * radius;
    for (;;) {
        double r;
        double acceptance;
        if (X < 2.0) {
            // Poisson Green proposal: r/R follows Beta(2, 2).
            const double a = -std::log(rng.unit_open() * rng.unit_open());
            const double b = -std::log(rng.unit_open() * rng.unit_open());
            r = radius * a / (a + b);
            const double proposal = (radius - r)
                                  / (4.0 * pi * r * radius);
            acceptance = green_3d(alpha, radius, r) / proposal;
        } else {
            const double time = -std::log(rng.unit_open()) / (alpha * alpha);
            const double scale = std::sqrt(2.0 * time);
            const double x0 = scale * normal(rng);
            const double x1 = scale * normal(rng);
            const double x2 = scale * normal(rng);
            r = std::sqrt(x0 * x0 + x1 * x1 + x2 * x2);
            if (r >= radius) continue;

            const double x = alpha * r;
            acceptance = (-std::expm1(-2.0 * (X - x)))
                       / (-std::expm1(-2.0 * X));
        }
        if (rng.unit() < clamp_probability(acceptance)) return r;
    }
}

} // namespace wos::screened
